{{- if and .Values.postgres.enabled (not .Values.database.existingSecret) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "listmonk.dbSecretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listmonk.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.user | quote }}
  database: {{ .Values.database.name | quote }}
  password: {{ if $existing }}{{ $existing.data.password | b64dec | quote }}{{ else }}{{ randAlphaNum 32 | quote }}{{ end }}
{{- end }}
