{{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listmonk.smtpSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-host: {{ .Values.smtp.host | quote }}
  smtp-port: {{ .Values.smtp.port | quote }}
  smtp-username: {{ .Values.smtp.username | quote }}
  smtp-password: {{ .Values.smtp.password | quote }}
  smtp-from: {{ .Values.smtp.from | quote }}
{{- end }}
